BasicUsageEnvironment: fix compilation on older toolchains
$ ./genMakefiles linux-64bit && make

```
BasicTaskScheduler.cpp: In member function ‘virtual void BasicTaskScheduler::SingleStep(unsigned int)’:
BasicTaskScheduler.cpp:191:40: error: ‘struct std::atomic_flag’ has no member named ‘test’
  191 |       if (fTriggersAwaitingHandling[i].test()) {
      |                                        ^~~~
```

https://en.cppreference.com/cpp/atomic/atomic_flag/test

test() is a C++20 feature, the code base does not require C++20
anywhere, so just use test_and_set() to allow compilation with C++11

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>