build: enforce C++20 standard across all platform configurations
std::atomic_flag::test is a C++20 feature [1]. Since GCC 10 fully supports
C++20 and there is no need to maintain compatibility with older C++
versions [2], enforce -std=c++20 across all 31 platform build configurations.

This ensures consistent C++20 features are available across all supported
platforms: Linux variants, BSD, macOS, Cygwin, Windows (MinGW), ARM,
AVR32, Blackfin, CRIS, Solaris, uClinux, QNX4, and iOS.

Fixes: std::atomic_flag::test usage

BasicTaskScheduler.cpp: In member function ‘virtual void BasicTaskScheduler::SingleStep(unsigned int)’:
BasicTaskScheduler.cpp:191:40: error: ‘struct std::atomic_flag’ has no member named ‘test’
  191 |       if (fTriggersAwaitingHandling[i].test()) {
      |                                        ^~~~

[1] https://en.cppreference.com/cpp/atomic/atomic_flag/test
[2] http://lists.live555.com/pipermail/live-devel/2026-June/022806.html

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>